# Generated by Django 2.1.5 on 2019-03-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190314_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='Slug',
            new_name='slug',
        ),
    ]
